/**
 * @author: oldj
 * @homepage: https://oldj.net
 */

export default {
  active_main_window: 'active_main_window',
  add_new: 'add_new',
  add_new_in_folder: 'add_new_in_folder',
  browser_link: 'browser_link',
  close_find: 'close_find',
  cmd_run_result: 'cmd_run_result',
  config_updated: 'config_updated',
  edit_dotfile_info: 'edit_dotfile_info',
  editor_content_change: 'editor:content_change',
  editor_gutter_click: 'editor:gutter_click',
  dotfile_content_changed: 'dotfile_content_changed',
  dotfile_refreshed: 'dotfile_refreshed',
  dotfile_refreshed_by_id: 'dotfile_refreshed_by_id',
  move_to_trashcan: 'move_to_trashcan',
  remove_dotfile_management: 'remove_dotfile_management',
  new_version: 'new_version',
  reload_list: 'reload_list',
  select_dotfile: 'select_dotfile',
  set_dotfile_on_status: 'set_dotfile_on_status',
  show_about: 'show_about',
  show_history: 'show_history',
  show_preferences: 'show_preferences',
  show_set_write_mode: 'show_set_write_mode',
  show_source: 'show_source',
  show_sudo_password_input: 'show_sudo_password_input',
  system_dotfile_updated: 'system_dotfile_updated',
  toggle_comment: 'toggle_comment',
  toggle_developer_tools: 'toggle_developer_tools',
  toggle_item: 'toggle_item',
  toggle_left_panel: 'toggle_left_panel',
  tray_list_updated: 'tray:list_updated',
  update_download_progress: 'update_download_progress',
  update_downloaded: 'update_downloaded',
  write_dotfile_to_system: 'write_dotfile_to_system',
}
